alias d='du -sh * | sort -h'
alias ll='ls -lshart'
alias ipe='curl ipinfo.io/ip'
alias pubip='curl ifconfig.io'
alias c='clear'
alias cpv='rsync -avhtP'
alias dc='docker-compose -f'
alias trash='mv --force -t /home/eric/.Trash'
alias gl='git log -p --stat --graph'
#alias gl='git log -p --stat'
# Enable aliases to be sudo'ed
alias sudo='sudo '
alias untar='tar xvf'
