#!/bin/bash
cd
pth=$HOME/.dotfiles
for dotfile in .vimrc .profile .inputrc .bashrc .bash_logout .bash_aliases .gitconfig
do
	if [ -f $HOME/$dotfile ]; then
		mv $HOME/$dotfile $HOME/$dotfile.$HOSTNAME
	fi

	ln -s $pth/$dotfile $HOME/$dotfile
done

if [ -d $HOME/.ssh ]; then
	tar -cvzf ~/$HOSTNAME.ssh.tgz .ssh
	rm -r ~/.ssh
fi

ln -s ~/.secure/.ssh ~/.ssh


if [ -d $HOME/.vim ]; then
	tar -cvzf ~/$HOSTNAME.vim.tgz .vim
	rm -r ~/.vim
fi

ln -s ~/.dotfiles/.vim ~/.vim

# Need to ensure secure files are in place first
gpg --import ~/.secure/.keys/eric.githubSigningKey.private
